services:
  discovery-service:
    build:
      context: ../buuchezobank-discovery-service
    container_name: discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - buuchezobank-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

    ports:
      - "9092:9092"
    networks:
      - buuchezobank-net

  api-gateway:
    build: ../buuchezobank-api-gateway
    container_name: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file: /home/ec2-user/projects/.env
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - buuchezobank-net

  user-account-service:
    build: .
    container_name: user-account-service
    depends_on:
      discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file: /home/ec2-user/projects/.env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - buuchezobank-net

  transaction-service:
    build: ../buuchezobank-transaction-service
    container_name: transaction-service
    depends_on:
      discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file: /home/ec2-user/projects/.env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - buuchezobank-net

  notification-service:
    build: ../buuchezobank-notification-service
    container_name: notification-service
    depends_on:
      discovery-service:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file: /home/ec2-user/projects/.env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - buuchezobank-net

networks:
  buuchezobank-net:
    driver: bridge